name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java 21 and Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-21-jdk maven

      - name: Remove previous JAR on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/
            rm -f bddAtcProject-0.0.1-SNAPSHOT.jar

      - name: Build and Deploy
        run: |
          cd /home/ec2-user/your-project-directory  # replace with your actual project directory
          mvn clean package
          scp -i /path/to/imkrsnakey.pem target/bddAtcProject-0.0.1-SNAPSHOT.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/
            nohup java -jar bddAtcProject-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
