name: Build, Deploy, and Run on EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Build JAR
        run: |
          cd "${{ github.workspace }}"  # Use the repository root as the project directory
          mvn clean package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v2
        with:
          name: bddAtcProject-0.0.1-SNAPSHOT
          path: target/bddAtcProject-0.0.1-SNAPSHOT.jar

  deploy_and_run:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: bddAtcProject-0.0.1-SNAPSHOT
          path: target

      - name: Remove previous JAR on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            rm -f /home/ec2-user/bddAtcProject-0.0.1-SNAPSHOT.jar

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: 'target/bddAtcProject-0.0.1-SNAPSHOT.jar'
          target: '/home/ec2-user/'

      - name: Run Spring Boot on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/target
            nohup java -jar bddAtcProject-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
            aws s3 cp bddAtcProject-0.0.1-SNAPSHOT.jar s3://unique-kindnesskettle-image/Artifacts/
