name: Build, Test, Deploy, and Run on EC2

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      stepsOutput: ${{ steps.maven-version.outputs.maven-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Install Maven
        id: maven-version
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          echo "maven-version=$(mvn -v | sed -n 's/.*Maven \([0-9.]*\).*/\1/p')" >> $GITHUB_ENV

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build without tests
        run: mvn clean package -DskipTests

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v2
        with:
          name: bddAtcProject-0.0.1-SNAPSHOT
          path: target/bddAtcProject-0.0.1-SNAPSHOT.jar

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Tests
        run: mvn test

  deploy_and_run:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: bddAtcProject-0.0.1-SNAPSHOT
          path: target

      - name: Remove previous JAR on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            PID=$(sudo lsof -t -i:8085)
            if [ ! -z "$PID" ]; then
              sudo kill -9 $PID
            fi
            rm -f /home/ec2-user/bddAtcProject-0.0.1-SNAPSHOT.jar

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: 'target/bddAtcProject-0.0.1-SNAPSHOT.jar'
          target: '/home/ec2-user/'

      - name: Run Spring Boot on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/target
            nohup java -jar bddAtcProject-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
