name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Display contents of the target directory
        run: ls -la target

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: bddAtcProject
          path: target/bddAtcProject-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Install SSH Client
        run: sudo apt-get install openssh-client

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Update known_hosts
        run: ssh-keyscan -H 18.200.248.149 >> ~/.ssh/known_hosts

      - name: Display contents of the target directory
        run: ls -la $GITHUB_WORKSPACE/target

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

          scp -i deploy_key.pem "$GITHUB_WORKSPACE/target/bddAtcProject-0.0.1-SNAPSHOT.jar" ec2-user@18.200.248.149:/home/ec2-user
          ssh -i deploy_key.pem ec2-user@18.200.248.149 "nohup java -jar /home/ec2-user/bddAtcProject-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &"
