deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Deploy to EC2
      run: |
        echo "$DEPLOY_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem
        scp -i deploy_key.pem "target/bddAtcProject-0.0.1-SNAPSHOT.jar" ec2-user@18.200.248.149:/home/ec2-user
        ssh -i deploy_key.pem ec2-user@18.200.248.149 "nohup java -jar /home/ec2-user/bddAtcProject-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &"
